namespace PrinterAgent.Domain;

/// <summary>
/// Published alongside <c>URSPrinterAgentSetup.exe</c> on GitHub Releases (generated by CI).
/// </summary>
public sealed class ReleaseManifest
{
    public required string Version { get; init; }
    public required string DownloadUrl { get; init; }
    public required string Sha256 { get; init; }
    public required string Signature { get; init; }
}
